### PR TITLE
DA Translation fix + Ru Translation

### PR DESCRIPTION
**Pull request by h9lk**

### CODE REVIEW

**Comment by sapphonie** [comment]
could you rebase this please

**Comment by h9lk** [comment]
try merge all commits into one when rebase, but git didn't want to change them re-read 10 manuals on git-rebase, i gave up

**Comment by sapphonie** [comment]
ok so, what exactly is the difference between this version and the one blueberry submitted? i've merged blueberry's into the main translation file, and I can't really see any glaring differences.

**Comment by h9lk** [comment]
> 
> 
> ok so, what exactly is the difference between this version and the one blueberry submitted? i've merged blueberry's into the main translation file, and I can't really see any glaring differences.

will try to substantiate my point of view as much as possible, trying not to defend my translation, but they radically differ in  approach to translation. I relied more on gaming style without translating key phrases as "aimbotting" or "spinbot" and tried not to translate literally. In translation that you specified, everything is translated thoroughly, as it is, it also takes separate file, also point out some translation inaccuracy in second case of network parameters and interpolation

**Comment by sapphonie** [comment]
aight, try to get it on the latest commit (aka all in one file) and ill merge it tomorrow. thanks.

**Comment by h9lk** [comment]
> 
> 
> aight, try to get it on the latest commit (aka all in one file) and ill merge it tomorrow. thanks.

will make a separate request to avoid further confusion

**Pull request closed without merging**
